### ISSUE TITLE
About errors in self-created kg file

### ISSUE THREAD

**Issue by KT1061** [krisds/koopa#32]
Hello krisds.
I created a kg file to analyze the Micro Focus Cobol source.
However, when he ran an analysis using this, a StackOverFlowError occurred.
My guess is that some syntax causes an infinite loop.
However, even after investigating the cause, I couldn't find a solution, so I would like to ask for help from the community.

I will give you the relevant kg file and the sample code used for analysis, so could you please investigate the cause?

The error that occurs is as follows.

```
java.lang.StackOverflowError: null
	at java.base/java.util.HashMap.hash(HashMap.java:339) ~[na:na]
	at java.base/java.util.HashMap.put(HashMap.java:607) ~[na:na]
	at java.base/java.util.HashSet.add(HashSet.java:220) ~[na:na]
	at koopa.core.grammars.combinators.MatchKeyword.addAllLeadingKeywordsTo(MatchKeyword.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.Scoped.addAllLeadingKeywordsTo(Scoped.java:180) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.NAryParserDecorator.addAllLeadingKeywordsTo(NAryParserDecorator.java:34) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.Scoped.addAllLeadingKeywordsTo(Scoped.java:180) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.NAryParserDecorator.addAllLeadingKeywordsTo(NAryParserDecorator.java:34) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.Scoped.addAllLeadingKeywordsTo(Scoped.java:180) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.Scoped.addAllLeadingKeywordsTo(Scoped.java:180) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.Scoped.addAllLeadingKeywordsTo(Scoped.java:180) ~[koopa-20230710.jar:na]
	at koopa.core.grammars.combinators.WrappedAs.addAllLeadingKeywordsTo(WrappedAs.java:58) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.Sequence.addAllLeadingKeywordsTo(Sequence.java:38) ~[koopa-20230710.jar:na]
	at koopa.core.parsers.combinators.UnaryParserDecorator.addAllLeadingKeywordsTo(UnaryParserDecorator.java:32) ~[koopa-20230710.jar:na]
	...
```

When I added the debug code that outputs name to Scoped.addAllLeadingKeywordsTo, I got the following result.
For some reason, programDefinition is being called many times.
Please investigate as we do not know the cause of this.

```
scope(programDefinition).addAllLeadingKeywordsTo(xxx)
scope(programIdParagraph).addAllLeadingKeywordsTo(xxx)
scope(programIdParagraph_format1).addAllLeadingKeywordsTo(xxx)
scope(programIdParagraph_format2).addAllLeadingKeywordsTo(xxx)
scope(programIdParagraph_format3).addAllLeadingKeywordsTo(xxx)
scope(programIdParagraph_format4).addAllLeadingKeywordsTo(xxx)
scope(replaceStatement).addAllLeadingKeywordsTo(xxx)
scope(optionsParagraph).addAllLeadingKeywordsTo(xxx)
scope(metadata).addAllLeadingKeywordsTo(xxx)
scope(environmentDivision).addAllLeadingKeywordsTo(xxx)
scope(dataDivision).addAllLeadingKeywordsTo(xxx)
scope(fileSection).addAllLeadingKeywordsTo(xxx)
scope(fileDescriptionEntry).addAllLeadingKeywordsTo(xxx)
scope(fileDescriptionEntry_format1).addAllLeadingKeywordsTo(xxx)
scope(fileDescriptionEntry_format2).addAllLeadingKeywordsTo(xxx)
scope(fileDescriptionEntry_format3).addAllLeadingKeywordsTo(xxx)
scope(fileDescriptionEntry_format4).addAllLeadingKeywordsTo(xxx)
scope(reportFileDescription).addAllLeadingKeywordsTo(xxx)
scope(workingStorageSection).addAllLeadingKeywordsTo(xxx)
scope(linkageSection).addAllLeadingKeywordsTo(xxx)
scope(communicationSection).addAllLeadingKeywordsTo(xxx)
scope(reportSection).addAllLeadingKeywordsTo(xxx)
scope(procedureDivision).addAllLeadingKeywordsTo(xxx)
scope(procedureDivision_format1).addAllLeadingKeywordsTo(xxx)
scope(procedureDivisionHeader).addAllLeadingKeywordsTo(xxx)
scope(procedureDivision_format3).addAllLeadingKeywordsTo(xxx)
scope(programDefinition).addAllLeadingKeywordsTo(xxx)
...
```
[KT1061.zip](https://github.com/krisds/koopa/files/12654841/KT1061.zip)

**Comment by krisds** [comment]
Hey KT1061, I'll try to take a look this weekend.

**Comment by krisds** [comment]
I think I have a working solution, but it's been so long since I actively worked on this logic that I want to mull it over a bit more.

**Comment by krisds** [comment]
I have just pushed a commit, which should fix the problem. I have tried it on your MF Cobol grammar, and was able to parse the example file you also shared.

Can you update, and try it for yourself ?

**Comment by KT1061** [comment]
I was able to resolve the issue by incorporating what you provided.
thank you.

**Comment by krisds** [comment]
👍
